### PR TITLE
Allow OIDCRemoteUserClaim from user info endpoint

### PR DESCRIPTION
**Pull request by steve-dave**
I apologise in advance if the current behaviour is by design, but found that REMOTE_USER could only be set from claims in id_token, not from the user info endpoint, even though the user info claims have already been retrieved when REMOTE_USER is set.  This patch removes this limitation.  My C is very rusty and I'm new to this codebase, so please advise if the patch requires refactoring.

### CODE REVIEW

**Comment by gwollman** [comment]
I ran into this issue as well, but never got around to figuring out how to fix it.

**Comment by zandbelt** [comment]
good stuff! one remark: the id_token is parsed already in jwt->payload.value.json; why would you need to parse it again?

**Comment by steve-dave** [comment]
@zandbelt that's just because I'm not familiar with the code.  I'll update the PR to use the pre-parsed object.

Thanks!

**Comment by steve-dave** [comment]
@zandbelt I've updated the PR, hopefully haven't missed anything else.

Thanks!

**Pull request merged**
