### PR TITLE
Add regex substitution for *RemoteUserClaims

### PR DESCRIPTION
**Pull request by hihellobolke**
Hello, 

I wanted to use extracted RemoteUserClaims using regex and also allow modification to it. I enhanced it to allow group substitution. The PCRE based substitution is from the [pcre_example](ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/Contrib/pcre_subst.tar.gz)

```
# OIDCOAuthRemoteUserClaim <claim-name> [<regular-expression>] [<substitution-string>]
# sub: user@domain.com 
# remote_user: domain_user
OIDCOAuthRemoteUserClaim  sub  ^(.*)@(.*)\.([^.]*)$  $2_$1
```

### CODE REVIEW

**Comment by zandbelt** [comment]
qq: is it backwards compatible?

**Comment by hihellobolke** [comment]
@zandbelt Yes should be.

The default <substitution-string> is "$1" so the first match group is selected, this would be backward compatible.
```
OIDCOAuthRemoteUserClaim  sub  ^(.*)@(.*)\.([^.]*)#
# this would be $1, first match
```

**Comment by zandbelt** [comment]
unfortunately it doesn't seem to be: 
```
OIDCRemoteUserClaim email ^(.*)@
```
renders `domain.com` instead of the former `user`. Can you fix that?

**Comment by zandbelt** [comment]
handled that myself; thanks for the contribution!

**Pull request merged**
